In [1]:
import numpy as np

### Creating Arrays

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
np.ones(3)

array([1., 1., 1.])

In [5]:
np.ones((4, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
np.full(7, 5)

array([5, 5, 5, 5, 5, 5, 5])

In [7]:
np.full((2, 3), 1)

array([[1, 1, 1],
       [1, 1, 1]])

In [8]:
np.array([5, 4, 3, 2, 1])

array([5, 4, 3, 2, 1])

In [9]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [10]:
np.arange(2, 7, 0.5)

array([2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5])

In [11]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [12]:
np.linspace(1, 10, 20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

### Indexing and Slicing Arrays

In [13]:
arr = np.array([[2, 3, 4], [5, 6, 7]])
arr[0]

array([2, 3, 4])

In [14]:
arr[:, 0]

array([2, 5])

### Generating Random Arrays

In [15]:
np.random.seed(2)
rarr = np.random.rand(5, 3)
rarr

array([[0.4359949 , 0.02592623, 0.54966248],
       [0.43532239, 0.4203678 , 0.33033482],
       [0.20464863, 0.61927097, 0.29965467],
       [0.26682728, 0.62113383, 0.52914209],
       [0.13457995, 0.51357812, 0.18443987]])

In [16]:
rarr2 = np.random.randint(low=0, high=100, size=(5, 3))
rarr2

array([[38, 33, 58],
       [67, 69, 88],
       [68, 46, 70],
       [95, 83, 31],
       [66, 80, 52]])

### Array Operations

In [17]:
arr

array([[2, 3, 4],
       [5, 6, 7]])

In [18]:
arr + 1

array([[3, 4, 5],
       [6, 7, 8]])

In [19]:
arr * 2

array([[ 4,  6,  8],
       [10, 12, 14]])

In [20]:
arr1 = np.ones(4)
arr2 = np.full(4, 3)
arr1 + arr2

array([4., 4., 4., 4.])

In [21]:
arr1 / arr2

array([0.33333333, 0.33333333, 0.33333333, 0.33333333])

In [23]:
arr > 3

array([[False, False,  True],
       [ True,  True,  True]])

In [25]:
arr[arr > 3] # get elements greater than 3

array([4, 5, 6, 7])

### Summary Operations

In [26]:
arr.min()

np.int64(2)

In [27]:
arr.max()

np.int64(7)

In [29]:
arr.sum()

np.int64(27)

In [30]:
arr.mean()

np.float64(4.5)

In [33]:
arr.std()

np.float64(1.707825127659933)